"""The Alembic chain must build the schema on an *empty* database.

CLAUDE.md rule 8 and .devnotes/teams/02_SCHEMA.md § 9.1: Postgres deploys start
empty, so `Base.metadata.create_all()` is not allowed to be what provisions a
new instance. This is the test that would have caught the blocker recorded as
T1.0 in .devnotes/teams/TASKS.md, where the first revision only ALTERed tables
that nothing had ever created.

Every test here runs against a fresh temp SQLite file. None of them may touch
`workspace.db` or the session database the rest of the suite shares — hence the
explicit `sqlalchemy.url` override on a Config built per test rather than
reliance on `config.DATABASE_URL`.

SQLite alone is not enough. Batch mode rebuilds a table from its new definition,
which silently papers over statements Postgres rejects outright — `b1a7c4e92f10`
adding a second PRIMARY KEY to `workspace_data` is exactly that, and it passed
every SQLite run while failing on the first empty Postgres deploy. The
`TEAMS_TEST_POSTGRES_URL` tests below cover that gap; they skip when no server is
configured, so set it before merging anything that touches a migration:

    TEAMS_TEST_POSTGRES_URL=postgresql+psycopg://user:pw@127.0.0.1:5435/postgres

The URL must point at a **maintenance** database (typically `postgres`) the test
can connect to in order to create and drop its own throwaway one.
"""
import os
import pathlib
import uuid

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext

import models

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

# Tables the chain is expected to build, including the four the Teams feature
# adds (M1-M3). `alembic_version` is Alembic's own bookkeeping.
EXPECTED_TABLES = {
    "users",
    "projects",
    "tasks",
    "labels",
    # `team_members` is renamed to `time_logs` by M4 — it was never a team, just
    # a name and a seconds counter (.devnotes/teams/01_DESIGN.md § 8).
    "time_logs",
    "workspace_data",
    "teams",
    "team_memberships",
    "project_grants",
    "task_reviews",
}


@pytest.fixture
def empty_db(tmp_path):
    """An Alembic Config pointed at a brand-new, genuinely empty SQLite file."""
    db_path = tmp_path / "chain.db"
    url = f"sqlite:///{db_path.as_posix()}"

    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    # `attributes`, not just `set_main_option`: env.py imports config at module
    # scope (which caches .env) and would otherwise overwrite the url with
    # config.DATABASE_URL — pointing these migrations at the deployment's real
    # Postgres database instead of this throwaway file.
    cfg.attributes["sqlalchemy.url"] = url

    assert not db_path.exists(), "the fixture must start from no database at all"
    yield cfg, url, db_path


def _table_names(url):
    engine = sa.create_engine(url)
    try:
        return set(sa.inspect(engine).get_table_names())
    finally:
        engine.dispose()


def _columns(url, table):
    engine = sa.create_engine(url)
    try:
        return {c["name"] for c in sa.inspect(engine).get_columns(table)}
    finally:
        engine.dispose()


def test_migration_chain_builds_on_empty_database(empty_db):
    """`upgrade head` from nothing produces the whole schema.

    The regression this pins: the chain's first revision was pure ALTER/CREATE
    INDEX output autogenerated against an already-populated database, so it
    failed on the first statement against an empty one.
    """
    cfg, url, _ = empty_db

    command.upgrade(cfg, "head")

    assert EXPECTED_TABLES <= _table_names(url)


def test_migration_chain_matches_the_orm(empty_db):
    """The built schema and models.py agree — no drift in either direction.

    A chain that runs but produces a different schema than the ORM expects fails
    later, at the first query, and much less legibly.
    """
    cfg, url, _ = empty_db

    command.upgrade(cfg, "head")

    engine = sa.create_engine(url)
    try:
        with engine.connect() as conn:
            diffs = compare_metadata(
                MigrationContext.configure(conn), models.Base.metadata
            )
    finally:
        engine.dispose()

    assert diffs == [], f"schema drift between migrations and models.py: {diffs}"


def test_migration_chain_downgrades_cleanly(empty_db):
    """`downgrade base` undoes everything, leaving only Alembic's version table.

    Downgrades that are written but never executed are downgrades that do not
    work; this is the cheapest place to find that out.
    """
    cfg, url, _ = empty_db

    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    assert _table_names(url) <= {"alembic_version"}


def test_teams_migrations_round_trip(empty_db):
    """The Teams revisions can be reversed and reapplied.

    Downgrading past M1 then `upgrade head` is the verification step named in
    .devnotes/teams/TASKS.md T1.2, and the case a partial rollout depends on.
    """
    cfg, url, _ = empty_db

    command.upgrade(cfg, "head")
    # Downgrade to the revision *before* M1 by name rather than by a relative
    # offset: `-3` silently points somewhere else the moment another migration
    # is added on top, which is exactly what M4 did.
    command.downgrade(cfg, "c2d8f1a390bb")

    after_downgrade = _table_names(url)
    for table in ("teams", "team_memberships", "project_grants", "task_reviews"):
        assert table not in after_downgrade
    assert "assigned_team_id" not in _columns(url, "tasks")
    assert "visibility" not in _columns(url, "projects")
    # M4's downgrade restores the old table name. It cannot restore rows deleted
    # while it was called time_logs — that limit is stated in its docstring.
    assert "team_members" in after_downgrade
    assert "time_logs" not in after_downgrade

    command.upgrade(cfg, "head")

    assert EXPECTED_TABLES <= _table_names(url)


def test_new_columns_exist_after_upgrade(empty_db):
    """The columns Phase 1 adds to the two existing tables are really there."""
    cfg, url, _ = empty_db

    command.upgrade(cfg, "head")

    task_columns = _columns(url, "tasks")
    assert {"assigned_team_id", "assignee_user_id"} <= task_columns

    project_columns = _columns(url, "projects")
    assert {
        "restrict_to_assigned_team",
        "require_distinct_reviewer",
        "visibility",
    } <= project_columns


def test_existing_rows_keep_todays_behaviour(empty_db):
    """The new project flags default to the pre-teams behaviour on old rows.

    M2 adds three NOT NULL columns to a table that already has rows in any real
    deployment. They carry a **server_default** rather than only a Python-side
    default, because a Python default does not populate existing rows during an
    ALTER TABLE. If that regressed, the migration would either fail outright on
    a non-empty table or leave rows whose flags silently change behaviour.
    """
    cfg, url, _ = empty_db

    # Stop before M2 and insert a project the way a pre-teams deployment would.
    command.upgrade(cfg, "d1e5a0c74b21")

    engine = sa.create_engine(url)
    try:
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO projects (name, slug, type, status, creator) "
                    "VALUES ('legacy', 'legacy', 'detection', 'active', 'someone')"
                )
            )

        command.upgrade(cfg, "head")

        with engine.connect() as conn:
            row = conn.execute(
                sa.text(
                    "SELECT restrict_to_assigned_team, require_distinct_reviewer, "
                    "visibility FROM projects WHERE slug = 'legacy'"
                )
            ).one()
    finally:
        engine.dispose()

    restrict, distinct_reviewer, visibility = row
    # Falsey rather than `is False`: SQLite stores booleans as 0/1.
    assert not restrict, "assignment must stay advisory for pre-teams projects"
    assert not distinct_reviewer
    assert visibility == "private"


def test_existing_tasks_land_in_the_shared_pool(empty_db):
    """A task that predates M3 has no team, which means the shared pool.

    NULL assigned_team_id is what makes the migration behaviour-neutral
    (.devnotes/teams/01_DESIGN.md § 3.3): every team with an annotate-capable
    grant may work it, exactly as every task is workable today. A backfill here
    would be a behaviour change, so there deliberately is not one.
    """
    cfg, url, _ = empty_db

    command.upgrade(cfg, "e2f6b1d85c32")

    engine = sa.create_engine(url)
    try:
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO projects (name, slug, type, status, creator) "
                    "VALUES ('p', 'p', 'detection', 'active', 'someone')"
                )
            )
            conn.execute(
                sa.text(
                    "INSERT INTO tasks (project_id, image_path, status) "
                    "VALUES (1, 'a.jpg', 'New')"
                )
            )

        command.upgrade(cfg, "head")

        with engine.connect() as conn:
            row = conn.execute(
                sa.text(
                    "SELECT assigned_team_id, assignee_user_id FROM tasks "
                    "WHERE image_path = 'a.jpg'"
                )
            ).one()
    finally:
        engine.dispose()

    assert row == (None, None)


# --- Postgres ----------------------------------------------------------------
#
# Production runs Postgres; dev runs SQLite. The two disagree about what DDL
# they accept, and SQLite is the more permissive of the pair *specifically*
# because Alembic emulates ALTER by rebuilding the table. Anything these tests
# skip is unverified on the backend that actually matters.

POSTGRES_URL = os.environ.get("TEAMS_TEST_POSTGRES_URL", "").strip()

requires_postgres = pytest.mark.skipif(
    not POSTGRES_URL,
    reason="set TEAMS_TEST_POSTGRES_URL to a maintenance database to run these",
)


@pytest.fixture
def empty_postgres():
    """A throwaway Postgres database, created empty and dropped afterwards.

    Created rather than reused: "empty" is the whole point of the test, and a
    database left over from a previous run is not empty.
    """
    admin = sa.create_engine(POSTGRES_URL, isolation_level="AUTOCOMMIT")
    name = f"teams_migtest_{uuid.uuid4().hex[:12]}"
    try:
        with admin.connect() as conn:
            conn.execute(sa.text(f'CREATE DATABASE "{name}"'))

        url = POSTGRES_URL.rsplit("/", 1)[0] + f"/{name}"
        cfg = Config(str(REPO_ROOT / "alembic.ini"))
        cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
        cfg.attributes["sqlalchemy.url"] = url

        try:
            yield cfg, url
        finally:
            with admin.connect() as conn:
                # Terminate stragglers first: DROP DATABASE fails while any
                # connection remains, and a failed test can leave one behind.
                conn.execute(
                    sa.text(
                        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                        "WHERE datname = :name AND pid <> pg_backend_pid()"
                    ),
                    {"name": name},
                )
                conn.execute(sa.text(f'DROP DATABASE IF EXISTS "{name}"'))
    finally:
        admin.dispose()


@requires_postgres
def test_chain_builds_on_empty_postgres(empty_postgres):
    """The chain runs end to end on the backend production actually uses.

    Regression pinned: `b1a7c4e92f10` rebuilt `workspace_data`'s primary key
    with `create_primary_key` but never dropped the existing one. Postgres
    rejects a second PRIMARY KEY ("multiple primary keys for table ... are not
    allowed"); SQLite's batch mode rebuilds the table from the new definition
    and never notices. It passed every SQLite run and failed on the first
    provisioning of an empty Postgres database.
    """
    cfg, url = empty_postgres

    command.upgrade(cfg, "head")

    assert EXPECTED_TABLES <= _table_names(url)


@requires_postgres
def test_postgres_chain_matches_the_orm(empty_postgres):
    cfg, url = empty_postgres

    command.upgrade(cfg, "head")

    engine = sa.create_engine(url)
    try:
        with engine.connect() as conn:
            diffs = compare_metadata(
                MigrationContext.configure(conn), models.Base.metadata
            )
    finally:
        engine.dispose()

    assert diffs == [], f"schema drift between migrations and models.py: {diffs}"


@requires_postgres
def test_postgres_workspace_data_has_the_composite_key(empty_postgres):
    """`workspace_data` ends up keyed on (key, owner_id), under the name the
    migration's own downgrade expects to find."""
    cfg, url = empty_postgres

    command.upgrade(cfg, "head")

    engine = sa.create_engine(url)
    try:
        pk = sa.inspect(engine).get_pk_constraint("workspace_data")
    finally:
        engine.dispose()

    assert set(pk["constrained_columns"]) == {"key", "owner_id"}
    assert pk["name"] == "pk_workspace_data"


@requires_postgres
def test_postgres_chain_downgrades_cleanly(empty_postgres):
    cfg, url = empty_postgres

    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    assert _table_names(url) <= {"alembic_version"}
