"""Add TeamMemberAssociation

Revision ID: 778d6e6a94e0
Revises: b2a80927d17c
Create Date: 2026-07-31 10:20:52.948352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778d6e6a94e0'
down_revision: Union[str, Sequence[str], None] = 'b2a80927d17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_name'], ['team_members.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_associations_id'), 'team_member_associations', ['id'], unique=False)
    op.create_index(op.f('ix_team_member_associations_member_name'), 'team_member_associations', ['member_name'], unique=False)
    op.create_index(op.f('ix_team_member_associations_team_id'), 'team_member_associations', ['team_id'], unique=False)
    
    # Migrate data
    op.execute("INSERT INTO team_member_associations (member_name, team_id) SELECT name, team_id FROM team_members WHERE team_id IS NOT NULL")
    
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        # SQLite names for FK constraints are often None unless explicitly named.
        # batch_op.drop_constraint handles it for Postgres/SQLite. 
        batch_op.drop_constraint(op.f('team_members_team_id_fkey'), type_='foreignkey')
        batch_op.drop_column('team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(op.f('team_members_team_id_fkey'), 'teams', ['team_id'], ['id'])
    
    # Migrate data back
    op.execute("UPDATE team_members SET team_id = tma.team_id FROM team_member_associations tma WHERE team_members.name = tma.member_name")
    op.drop_index(op.f('ix_team_member_associations_team_id'), table_name='team_member_associations')
    op.drop_index(op.f('ix_team_member_associations_member_name'), table_name='team_member_associations')
    op.drop_index(op.f('ix_team_member_associations_id'), table_name='team_member_associations')
    op.drop_table('team_member_associations')
    # ### end Alembic commands ###
