"""Add annotations table

Revision ID: 7b8bc09aaa9a
Revises: 8418a8e3f66f
Create Date: 2026-08-09 16:35:28.696219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8bc09aaa9a'
down_revision: Union[str, Sequence[str], None] = '8418a8e3f66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.alter_column('annotations', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
