"""Initial migration

Revision ID: 97472310f3a2
Revises: 0000baseline01
Create Date: 2026-07-06 17:07:37.325375

NOTE: this revision only ALTERs and CREATE INDEXes — it was autogenerated against
an already-populated database and never created any table. The tables it alters
are created by `0000baseline01`, inserted underneath it so the chain builds on an
empty database (CLAUDE.md rule 8).

Its bare `op.alter_column` calls are not wrapped in `op.batch_alter_table`, so
they cannot run on SQLite at all — this revision has only ever been `stamp`ed,
never executed. `0000baseline01` therefore creates the tables in the shape this
revision would have *produced*, and `_already_current()` below turns the body
into a no-op in that case.

The ALTER/CREATE INDEX body itself is deliberately unmodified: production has
this revision stamped, and rewriting applied history would desynchronise the two
databases. On any database that genuinely predates it, the guard is false and the
original statements run exactly as before.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97472310f3a2'
down_revision: Union[str, Sequence[str], None] = '0000baseline01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _already_current() -> bool:
    """True when 0000baseline01 created the tables in this revision's end state.

    Detected by the one column this revision drops: `projects.time_spent` is
    present on every database that predates this revision and absent on one built
    by the baseline. Cheap, unambiguous, and needs no version table lookup.
    """
    columns = sa.inspect(op.get_bind()).get_columns('projects')
    return not any(c['name'] == 'time_spent' for c in columns)


def upgrade() -> None:
    """Upgrade schema."""
    if _already_current():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'creator',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_column('projects', 'time_spent')
    op.alter_column('tasks', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('tasks', 'image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'New'"))
    op.alter_column('tasks', 'assignee',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.alter_column('team_members', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_team_members_name'), 'team_members', ['name'], unique=False)
    op.alter_column('workspace_data', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_workspace_data_key'), 'workspace_data', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Mirror of the upgrade guard: on a baseline-built database this revision
    # changed nothing, so it must undo nothing. 0000baseline01's downgrade drops
    # the tables outright.
    if _already_current():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_data_key'), table_name='workspace_data')
    op.alter_column('workspace_data', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_team_members_name'), table_name='team_members')
    op.alter_column('team_members', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'assignee',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'New'"))
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'image_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('projects', sa.Column('time_spent', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'creator',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
