"""Rebuild notifications with the right recipient and timezone-aware timestamps

Revision ID: a7f3c9d20e14
Revises: f1c2d3e4a5b6
Create Date: 2026-09-10 14:20:00.000000

The original notifications migration (1e613d9e0c65) was autogenerated and never
adjusted, leaving three defects. It has never been applied to the deployment
database (which sits behind it), and the feature it backed was dead code, so
there are no rows to preserve — this migration drops and recreates the table
rather than issuing a series of ALTERs.

1. `recipient_name` pointed at `users.username`. The LAN deployment shares one
   login, so a username identifies the *account*, not a person, and could never
   address "the assignee" or "the owner". The recipient is an annotator, i.e.
   `team_members.name` — the identity carried by X-Annotator-Name and already
   stored in `tasks.assignee` and `projects.creator`.

2. `created_at` was a naive `sa.DateTime()` with `server_default=sa.text('now())`.
   Naive columns violate CLAUDE.md rule 7 (Postgres strips tzinfo and hands back
   a naive value, which then mis-compares against aware datetimes), and `now()`
   is not a SQLite function, so the default would fail outright in development
   and in the test suite.

3. `is_read` was nullable, so "unread" had two representations (0 and NULL) and
   the `is_read == 0` filter silently hid NULL rows.

Recreating rather than ALTERing is also what keeps the chain buildable on an
empty database (CLAUDE.md rule 8): 1e613d9e0c65 creates the table, this revision
replaces it, and a fresh Postgres deploy runs both in order.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f3c9d20e14'
down_revision: Union[str, Sequence[str], None] = 'f1c2d3e4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Conditional, not an unconditional drop: the deployment database is
    # stamped at the parent revision but has no `notifications` table (the
    # chain was stamped rather than fully executed at some point), so a plain
    # drop_table fails there with "table does not exist". Inspecting the live
    # schema makes this revision correct on both a database that ran
    # 1e613d9e0c65 and one that only recorded it.
    bind = op.get_bind()
    if sa.inspect(bind).has_table('notifications'):
        op.drop_table('notifications')

    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('recipient_name', sa.String(), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Integer(), nullable=False, server_default='0'),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.func.now(), nullable=False,
        ),
        sa.ForeignKeyConstraint(['recipient_name'], ['team_members.name'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'])
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'])
    # The only hot query is "my unread notices, newest first"; this composite
    # serves the filter and the ordering together.
    op.create_index(
        'ix_notifications_recipient_unread',
        'notifications', ['recipient_name', 'is_read', 'created_at'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')

    # Restore the shape 1e613d9e0c65 created, so the chain is reversible.
    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('recipient_name', sa.String(), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['recipient_name'], ['users.username'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'])
    op.create_index(op.f('ix_notifications_recipient_name'), 'notifications', ['recipient_name'])
