"""remove assignee from projects

Revision ID: aad187952884
Revises: c36e1c92c2a4
Create Date: 2026-07-30 17:17:28.219348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad187952884'
down_revision: Union[str, Sequence[str], None] = 'c36e1c92c2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'assignee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
