"""add team_id to projects

Revision ID: c36e1c92c2a4
Revises: 09022dfbd97f
Create Date: 2026-07-30 17:03:25.439415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36e1c92c2a4'
down_revision: Union[str, Sequence[str], None] = '09022dfbd97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'team_id')
    # ### end Alembic commands ###
