"""make timestamp columns timezone-aware

Revision ID: e6a762594f8e
Revises: 49021da7f1d9
Create Date: 2026-08-21 18:52:51.980754

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6a762594f8e'
down_revision: Union[str, Sequence[str], None] = '49021da7f1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Every existing naive TIMESTAMP value in this app was written as UTC wall-clock
    time (datetime.now(timezone.utc) in Python, or Postgres server_default now()
    on a server configured for Etc/UTC — see api/routers/tasks.py's datetime
    handling and CLAUDE.md rule 7). Postgres's implicit TIMESTAMP -> TIMESTAMPTZ
    cast reinterprets naive values using the session's `TimeZone` setting, which
    is not guaranteed to be UTC; an explicit `USING col AT TIME ZONE 'UTC'` makes
    that reinterpretation correct regardless of the session running this migration.

    SQLite has no native tz-aware timestamp type — it stores DateTime the same
    way regardless of timezone=True — so there is nothing to migrate there, and
    this raw Postgres `USING` SQL can't run against it (unlike an op.alter_column,
    it isn't batch-mode-rewritable). Skip entirely on SQLite, mirroring the
    sqlite_ignore_check pattern used elsewhere in this migration chain.
    """
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust ###
    op.execute("ALTER TABLE ai_jobs ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE annotations ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE export_jobs ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE projects ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE task_locks ALTER COLUMN claimed_at TYPE TIMESTAMP WITH TIME ZONE USING claimed_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE tasks ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE tasks ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE team_members ALTER COLUMN last_active_at TYPE TIMESTAMP WITH TIME ZONE USING last_active_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE teams ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Symmetric with upgrade(): reinterpret the tz-aware value back to UTC wall-clock
    naive text rather than relying on the implicit cast honoring the migrating
    session's TimeZone setting. No-op on SQLite for the same reason as upgrade().
    """
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust ###
    op.execute("ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE teams ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE team_members ALTER COLUMN last_active_at TYPE TIMESTAMP WITHOUT TIME ZONE USING last_active_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE tasks ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE USING updated_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE tasks ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE task_locks ALTER COLUMN claimed_at TYPE TIMESTAMP WITHOUT TIME ZONE USING claimed_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE projects ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE export_jobs ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE annotations ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE ai_jobs ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###
