"""Build the dev database schema from ORM metadata, then stamp Alembic at head.

Why not plain `alembic upgrade head`: the migration chain cannot build an
EMPTY database. Its first revision (97472310f3a2 "Initial migration") was
autogenerated against an already-populated SQLite DB, so it opens with
`ALTER TABLE projects ...` on a table nothing ever created. That is the
CLAUDE.md rule 8 violation ("migrations must build the schema on an empty
database"), and fixing the chain is a separate job.

Until then the dev database is built the way the test suite builds its
schema (tests/conftest.py): straight from Base.metadata. The chain is then
stamped at head so subsequent, well-formed migrations apply normally.

Refuses to run against anything but a *_dev database.
"""
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from alembic import command  # noqa: E402
from alembic.config import Config  # noqa: E402

from database import engine  # noqa: E402
from models import Base  # noqa: E402

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def main() -> int:
    url = str(engine.url)
    if not engine.url.database or not engine.url.database.endswith("_dev"):
        print(f"REFUSING: target database is not a *_dev database ({url})")
        return 1

    print(f"target: {engine.url.host}:{engine.url.port}/{engine.url.database}")

    Base.metadata.create_all(bind=engine)
    print(f"created {len(Base.metadata.tables)} tables from ORM metadata")

    cfg = Config(os.path.join(REPO_ROOT, "alembic.ini"))
    cfg.set_main_option("script_location", os.path.join(REPO_ROOT, "alembic"))
    command.stamp(cfg, "head")
    print("stamped alembic at head")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
