#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Install the annotation app as a Windows service that starts on boot
    and restarts automatically on crash (T0.4).

.DESCRIPTION
    Uses the Windows Task Scheduler (no third-party tools needed) to run
    uvicorn as a background service:
      - Starts on system boot (before any user logs in).
      - Restarts up to 3 times on failure with a 10-second delay.
      - Writes stdout/stderr to DATA_DIR\logs\service.log via a wrapper.

    Run once as Administrator from the repo root:
        .\scripts\install-service.ps1

    To remove:
        Unregister-ScheduledTask -TaskName "AnnotationApp" -Confirm:$false

    POWER PLAN: This script also sets the active power plan to "High
    Performance" so the serving PC never sleeps or hibernates mid-shift.
    Run separately if you only want the power change:
        powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c

.NOTES
    If you already have NSSM installed, replace the Task Scheduler approach
    with:
        nssm install AnnotationApp "venv\Scripts\uvicorn.exe" "main:app --host 0.0.0.0 --port 8000"
        nssm set AnnotationApp AppDirectory <repo-root>
        nssm set AnnotationApp AppEnvironmentExtra @(Get-Content .env)
        nssm start AnnotationApp
#>

$ErrorActionPreference = "Stop"

$repoRoot  = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$uvicorn   = Join-Path $repoRoot "venv\Scripts\uvicorn.exe"
$wrapperPs = Join-Path $repoRoot "scripts\_service-wrapper.ps1"

if (-not (Test-Path $uvicorn)) {
    Write-Error "venv not found at $uvicorn — run: python -m venv venv && venv\Scripts\pip install -r requirements.txt"
    exit 1
}

# --- Write a wrapper that loads .env then execs uvicorn -------------------
@'
# Auto-generated by install-service.ps1 — do not edit by hand.
# Loads .env, then starts uvicorn. Stdout/stderr go to the log file.
$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $repoRoot

# Load .env
$envFile = Join-Path $repoRoot ".env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        $_.Trim() | Where-Object { $_ -and -not $_.StartsWith('#') } | ForEach-Object {
            if ($_ -match '^\s*(\w+)\s*=\s*(.+)\s*$') {
                $val = $Matches[2].Trim().Trim('"').Trim("'")
                Set-Item -Path "env:$($Matches[1])" -Value $val
            }
        }
    }
}

$logDir = if ($env:DATA_DIR) { "$env:DATA_DIR\logs" } else { "$repoRoot\logs" }
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$log = Join-Path $logDir "service.log"

$host_ = if ($env:APP_HOST) { $env:APP_HOST } else { "0.0.0.0" }
$port  = if ($env:APP_PORT)  { $env:APP_PORT  } else { "8000" }

# Loop so that if uvicorn exits unexpectedly the wrapper restarts it.
while ($true) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $log -Value "$ts  [service] Starting uvicorn on $host_:$port"
    & "$repoRoot\venv\Scripts\uvicorn.exe" main:app --host $host_ --port $port 2>&1 |
        ForEach-Object { Add-Content -Path $log -Value "$(Get-Date -Format 'HH:mm:ss')  $_" }
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $log -Value "$ts  [service] uvicorn exited — restarting in 5s"
    Start-Sleep -Seconds 5
}
'@ | Set-Content -Path $wrapperPs -Encoding UTF8

Write-Host "Wrapper script written to $wrapperPs"

# --- Register the scheduled task -----------------------------------------
$taskName = "AnnotationApp"
$action   = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -WindowStyle Hidden -File `"$wrapperPs`"" `
    -WorkingDirectory $repoRoot

# AtStartup trigger fires before any user logs in.
$trigger  = New-ScheduledTaskTrigger -AtStartup
$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Days 365) `   # effectively unlimited
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Seconds 10) `
    -StartWhenAvailable

$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "Removed existing task '$taskName'."
}

Register-ScheduledTask `
    -TaskName  $taskName `
    -Action    $action `
    -Trigger   $trigger `
    -Settings  $settings `
    -Principal $principal `
    -Description "Annotation workspace — auto-start + auto-restart on boot" `
    | Out-Null

Write-Host "✓ Service task '$taskName' registered."

# --- No-sleep power plan --------------------------------------------------
Write-Host "Setting power plan to High Performance (no sleep/hibernate)..."
try {
    # GUID for the built-in High Performance plan.
    powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
    # Belt-and-suspenders: also disable sleep and hibernation timeouts.
    powercfg /change standby-timeout-ac 0
    powercfg /change hibernate-timeout-ac 0
    powercfg /hibernate off
    Write-Host "✓ Power plan set — PC will not sleep while plugged in."
} catch {
    Write-Warning "Could not set power plan: $_  (run manually: powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c)"
}

Write-Host ""
Write-Host "Start now : Start-ScheduledTask -TaskName '$taskName'"
Write-Host "Stop      : Stop-ScheduledTask  -TaskName '$taskName'"
Write-Host "Logs      : `$env:DATA_DIR\logs\service.log"
Write-Host "Uninstall : Unregister-ScheduledTask -TaskName '$taskName' -Confirm:`$false"
