#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Install the annotation app as a Windows service that starts on boot
    and restarts automatically on crash (T0.4).

.DESCRIPTION
    Uses the Windows Task Scheduler (no third-party tools needed) to run
    uvicorn as a background service:
      - Starts on system boot (before any user logs in).
      - Restarts up to 3 times on failure, 1 minute apart (Task Scheduler
        rejects a shorter interval); uvicorn crashes are actually handled
        much faster by the wrapper's own 5-second restart loop.
      - Writes stdout/stderr to DATA_DIR\logs\stdout.log via a wrapper
        (rotated at start). The app's own structured request log is written
        separately to DATA_DIR\logs\service\<date>\<METHOD>.log.

    Run once as Administrator from the repo root:
        .\scripts\install-service.ps1

    To remove:
        Unregister-ScheduledTask -TaskName "AnnotationApp" -Confirm:$false

    POWER: This script disables sleep/hibernate on AC power so the serving
    PC doesn't sleep mid-shift, and raises the minimum processor state to 50%
    on AC for responsiveness under load. It does NOT switch your active power
    plan - an earlier version force-switched to the built-in "High
    performance" plan, whose 100% minimum CPU frequency causes sustained heat
    and thermal throttling on a laptop. 50% is the deliberate middle ground.
    If you want just the sleep change without running the whole script:
        powercfg /change standby-timeout-ac 0
        powercfg /change hibernate-timeout-ac 0

.NOTES
    If you already have NSSM installed, replace the Task Scheduler approach
    with:
        nssm install AnnotationApp "venv\Scripts\uvicorn.exe" "main:app --host 0.0.0.0 --port 8000"
        nssm set AnnotationApp AppDirectory <repo-root>
        nssm set AnnotationApp AppEnvironmentExtra @(Get-Content .env)
        nssm start AnnotationApp
#>

$ErrorActionPreference = "Stop"

$repoRoot  = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$uvicorn   = Join-Path $repoRoot "venv\Scripts\uvicorn.exe"
$wrapperPs = Join-Path $repoRoot "scripts\_service-wrapper.ps1"

if (-not (Test-Path $uvicorn)) {
    Write-Error "venv not found at $uvicorn - run: python -m venv venv, then venv\Scripts\pip install -r requirements.txt"
    exit 1
}

# --- Write a wrapper that loads .env then execs uvicorn -------------------
@'
# Auto-generated by install-service.ps1 - do not edit by hand.
# Loads .env, then starts uvicorn. Stdout/stderr go to the log file.
# $PSScriptRoot is set for -File invocations and does not depend on how the
# task launched us, unlike $MyInvocation.MyCommand.Path.

# Bootstrap log: catches anything that kills this script before $log is set.
# Without it, a failure here exits silently and Task Scheduler reports only
# "LastTaskResult: 1" with an empty stdout.log - undiagnosable.
$bootLog = Join-Path $env:TEMP "annotation-service-boot.log"
function Write-Boot([string]$m) {
    try { Add-Content -Path $bootLog -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $m" } catch { }
}
trap {
    Write-Boot "FATAL: $($_.Exception.Message)"
    exit 1
}
Write-Boot "wrapper started (PSScriptRoot=$PSScriptRoot user=$env:USERNAME temp=$env:TEMP)"

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot
Write-Boot "repoRoot=$repoRoot"

# Load .env
$envFile = Join-Path $repoRoot ".env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        $_.Trim() | Where-Object { $_ -and -not $_.StartsWith('#') } | ForEach-Object {
            if ($_ -match '^\s*(\w+)\s*=\s*(.+)\s*$') {
                # Char literals, not quoted strings: a single quote written
                # inside a double-quoted string here breaks the Windows
                # PowerShell 5.1 parser that runs this wrapper.
                $val = $Matches[2].Trim().Trim([char]34).Trim([char]39)
                Set-Item -Path "env:$($Matches[1])" -Value $val
            }
        }
    }
}

$logDir = if ($env:DATA_DIR) { "$env:DATA_DIR\logs" } else { "$repoRoot\logs" }
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
# stdout.log, NOT service.log. The app now writes its own structured request
# record under logs\service\<date>\<METHOD>.log (.devnotes/logging/02_PLAN.md),
# and two different files called "service" - one the app's, one a raw stdout
# scrape - is a guaranteed source of confusion during an incident. This file is
# now only what it always actually was: whatever uvicorn printed, kept for
# stack traces and startup failures.
$log = Join-Path $logDir "stdout.log"

# Rotate at start rather than on a timer. The wrapper runs again on every boot
# and on every uvicorn crash, so this fires often enough - and the previous
# arrangement (plain Add-Content, forever) left a 56 MB service.log and a
# 101 MB orphan on the deploy box, which could only be truncated by stopping
# the service (01_AUDIT.md P1).
$maxStdoutBytes = 20MB
if ((Test-Path $log) -and ((Get-Item $log).Length -gt $maxStdoutBytes)) {
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    Move-Item -Path $log -Destination (Join-Path $logDir "stdout.log.$stamp") -Force
}
# Prune archived captures beyond the retention window. Matches the app's own
# LOG_RETENTION_DAYS so the two halves of the log directory age out together.
$retentionDays = if ($env:LOG_RETENTION_DAYS) { [int]$env:LOG_RETENTION_DAYS } else { 30 }
Get-ChildItem -Path $logDir -Filter "stdout.log.*" -ErrorAction SilentlyContinue |
    Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-$retentionDays) } |
    Remove-Item -Force -ErrorAction SilentlyContinue

# Not named 'host' - that is a read-only PowerShell automatic variable.
# Always brace-delimit these inside strings, as ${bindHost} and ${port}.
# Writing them undelimited before a colon makes Windows PowerShell 5.1 read
# the name-plus-colon as a drive-qualified variable reference, which fails to
# parse the entire file.
$bindHost = if ($env:APP_HOST) { $env:APP_HOST } else { "0.0.0.0" }
$port     = if ($env:APP_PORT) { $env:APP_PORT } else { "8000" }

# Refuse to start if something else already owns the port. Without this the
# wrapper restart-loops forever writing "address in use" while a stray
# process keeps serving - the confusing failure mode of having started
# uvicorn by hand before installing the service.
$inUse = Get-NetTCPConnection -LocalPort ([int]$port) -State Listen -ErrorAction SilentlyContinue
if ($inUse) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $owners = ($inUse.OwningProcess | Sort-Object -Unique) -join ", "
    Add-Content -Path $log -Value "$ts  [service] ABORT: port $port already in use by PID(s) $owners."
    Add-Content -Path $log -Value "$ts  [service]        If that is a manually started uvicorn, stop it, then:"
    Add-Content -Path $log -Value "$ts  [service]        Start-ScheduledTask -TaskName 'AnnotationApp'"
    exit 1
}

# Wait for the database to accept connections before starting uvicorn.
# Postgres (in Docker or otherwise) commonly takes 5-15s longer than uvicorn
# to come up after a reboot; without this wait, the app starts first and
# every early request stalls on an OS-level TCP timeout (20s+ on Windows)
# instead of failing fast, which is what "the app hangs after a reboot"
# usually turns out to be. SQLite has no such dependency, so this only
# applies when DATABASE_URL points at Postgres.
if ($env:DATABASE_URL -match '^postgresql(\+\w+)?://[^@]*@([^:/]+)(:(\d+))?/') {
    $dbHostToWaitFor = $Matches[2]
    $dbPortToWaitFor = if ($Matches[4]) { [int]$Matches[4] } else { 5432 }
    $waitDeadline = (Get-Date).AddMinutes(5)
    $everLogged = $false
    while ((Get-Date) -lt $waitDeadline) {
        $ready = Test-NetConnection -ComputerName $dbHostToWaitFor -Port $dbPortToWaitFor -InformationLevel Quiet -WarningAction SilentlyContinue
        if ($ready) { break }
        if (-not $everLogged) {
            Add-Content -Path $log -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  [service] waiting for Postgres on ${dbHostToWaitFor}:${dbPortToWaitFor}..."
            $everLogged = $true
        }
        Start-Sleep -Seconds 3
    }
    if ($everLogged) {
        $verb = if ($ready) { "reachable" } else { "still unreachable after 5 minutes, starting anyway" }
        Add-Content -Path $log -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  [service] Postgres ${verb}"
    }
}

# Loop so that if uvicorn exits unexpectedly the wrapper restarts it.
while ($true) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $log -Value "$ts  [service] Starting uvicorn on ${bindHost}:${port}"
    & "$repoRoot\venv\Scripts\uvicorn.exe" main:app --host $bindHost --port $port 2>&1 |
        ForEach-Object { Add-Content -Path $log -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $_" }
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $log -Value "$ts  [service] uvicorn exited - restarting in 5s"
    Start-Sleep -Seconds 5
}
'@ | Set-Content -Path $wrapperPs -Encoding utf8BOM

# The scheduled task runs this wrapper with powershell.exe (Windows PowerShell
# 5.1), which assumes the legacy ANSI codepage for files with no BOM. Written
# BOM-less, any non-ASCII character is misdecoded and can break parsing - an
# em-dash inside a double-quoted string swallowed the closing quote and made
# the whole file unparseable. The wrapper body is therefore kept ASCII-only
# AND written with a BOM, so neither safeguard depends on the other.
$wrapperBytes = [System.IO.File]::ReadAllBytes($wrapperPs)
if ($wrapperBytes | Where-Object { $_ -gt 127 } | Select-Object -First 1) {
    if ($wrapperBytes[0] -ne 0xEF) {
        Write-Error "Generated wrapper contains non-ASCII characters but no BOM; Windows PowerShell would misparse it."
        exit 1
    }
}

Write-Host "Wrapper script written to $wrapperPs"

# --- Register the scheduled task -----------------------------------------
$taskName = "AnnotationApp"
# -ExecutionPolicy Bypass is required, not optional. The machine's
# LocalMachine execution policy is commonly RemoteSigned, and the wrapper is
# an unsigned, locally-generated script. An interactive shell often has a
# looser per-process policy, so running the wrapper by hand succeeds while
# the scheduled task - which gets a fresh powershell.exe with no such
# override - refuses to run it and exits 1 *before executing any line*,
# producing the baffling combination of LastTaskResult=1 with a completely
# empty stdout.log.
# -NoProfile also matters: a profile that errors under SYSTEM would take the
# wrapper down with it, and profiles are irrelevant to a service anyway.
$action   = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$wrapperPs`"" `
    -WorkingDirectory $repoRoot

# AtStartup trigger fires before any user logs in.
$trigger  = New-ScheduledTaskTrigger -AtStartup
# RestartInterval must be >= 1 minute: Task Scheduler rejects anything shorter
# with "value ... incorrectly formatted or out of range (Interval:PT10S)".
# This only covers the wrapper *script* dying; uvicorn crashes are handled far
# faster by the wrapper's own 5-second restart loop, so a 1-minute floor here
# costs nothing in practice.
#
# BATTERY: the two battery switches are required, not cosmetic. Task Scheduler
# defaults DisallowStartIfOnBatteries and StopIfGoingOnBatteries to TRUE, so on
# a laptop the task is KILLED the instant the charger is unplugged - wrapper and
# uvicorn together. That is invisible in stdout.log: the wrapper is what writes
# both "uvicorn exited - restarting in 5s" and the restart loop, so when it dies
# too the log simply stops mid-request with no exit marker and no traceback, and
# nothing restarts until the next boot (AtStartup is the only trigger). Postgres
# is unaffected because it is a real Windows service, which makes it look like
# an app crash rather than a power event. Diagnosed from four outages whose last
# log line matched a Kernel-Power 105 "AcOnline=false" to the second.
$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Days 365) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -StartWhenAvailable `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries

$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest

# Registering requires elevation. Without this check the failure surfaces as a
# confusing "Access is denied" from Register-ScheduledTask several lines later.
$isAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Error "This script must be run as Administrator (right-click PowerShell -> Run as administrator)."
    exit 1
}

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "Removed existing task '$taskName'."
}

# -ErrorAction Stop so a registration failure aborts the script instead of
# falling through to print a success message for a task that does not exist.
Register-ScheduledTask `
    -TaskName  $taskName `
    -Action    $action `
    -Trigger   $trigger `
    -Settings  $settings `
    -Principal $principal `
    -Description "Annotation workspace - auto-start + auto-restart on boot" `
    -ErrorAction Stop `
    | Out-Null

# Confirm it is really there rather than trusting the call returned quietly.
if (-not (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue)) {
    Write-Error "Task '$taskName' was not registered. Nothing is supervising the app."
    exit 1
}

Write-Host "Service task '$taskName' registered."

# The battery switches above are the difference between "stays up when someone
# unplugs the charger" and "dies silently mid-shift", so confirm they actually
# took rather than trusting the switches. Registering with an older/patched
# Task Scheduler that ignored them would otherwise fail silently.
$applied = (Get-ScheduledTask -TaskName $taskName).Settings
if ($applied.DisallowStartIfOnBatteries -or $applied.StopIfGoingOnBatteries) {
    Write-Warning ("Battery settings did not apply " +
        "(DisallowStartIfOnBatteries=$($applied.DisallowStartIfOnBatteries), " +
        "StopIfGoingOnBatteries=$($applied.StopIfGoingOnBatteries)). " +
        "The app will be killed when this machine is unplugged. Fix with:")
    Write-Warning "  `$t = Get-ScheduledTask -TaskName '$taskName'"
    Write-Warning "  `$t.Settings.DisallowStartIfOnBatteries = `$false"
    Write-Warning "  `$t.Settings.StopIfGoingOnBatteries     = `$false"
    Write-Warning "  Set-ScheduledTask -TaskName '$taskName' -Settings `$t.Settings"
} else {
    Write-Host "Battery settings verified: task survives running on / switching to battery."
}

# --- No-sleep, on whatever plan is already active -------------------------
# Earlier versions of this script force-switched the active plan to the
# built-in "High performance" plan. That silently abandoned any custom plan
# already configured (this machine had four others: a "Ultimate Power Plan",
# "Balanced", and two custom ones) and, worse, "High performance" sets
# Minimum processor state to 100% on AC - the CPU never downclocks even at
# idle. On a laptop that means sustained max clock speed, more heat, and on
# thermally-limited hardware, throttling and slowdowns once it gets hot -
# i.e. exactly the "sluggish/freezy" symptom this caused after being run.
#
# The actual goal here is narrower: don't let the PC sleep mid-shift. That
# does not require switching plans or touching processor throttling at all -
# only the sleep/hibernate timeouts, applied to whichever plan the operator
# already has active.
#
# Both AC *and* DC. An earlier version set only the -ac timeouts, which left
# the Windows default of standby-timeout-dc = 10 minutes in place: unplug the
# serving laptop and it sleeps mid-shift, dropping every annotator. If this
# machine is a desktop the -dc settings are simply inert, so applying them
# unconditionally costs nothing.
#
# Processor throttling IS touched, but only the AC minimum, and only to 50% -
# not the 100% that stock "High performance" applies. 50% keeps the serving
# box off its lowest clocks (which showed up as lag on first request after an
# idle period) without holding it at max clock and cooking it. Battery (DC) is
# left alone so an unplugged machine still downclocks normally.
Write-Host "Disabling sleep/hibernate on the current power plan (no plan switch)..."
try {
    powercfg /change standby-timeout-ac 0
    powercfg /change hibernate-timeout-ac 0
    powercfg /change standby-timeout-dc 0
    powercfg /change hibernate-timeout-dc 0
    powercfg /hibernate off
    powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMIN 50
    powercfg /setactive SCHEME_CURRENT
    $current = (powercfg /getactivescheme)
    Write-Host "Sleep/hibernate disabled on AC and battery; min processor state (AC) set to 50%. Active plan unchanged: $current"
} catch {
    Write-Warning "Could not change sleep/hibernate settings: $_  (run manually: powercfg /change standby-timeout-ac 0; powercfg /change standby-timeout-dc 0)"
}

Write-Host ""
Write-Host "Start now : Start-ScheduledTask -TaskName '$taskName'"
Write-Host "Stop      : Stop-ScheduledTask  -TaskName '$taskName'"
Write-Host "Logs      : `$env:DATA_DIR\logs\service\<date>\<METHOD>.log  (requests)"
Write-Host "            `$env:DATA_DIR\logspp.log                        (application)"
Write-Host "            `$env:DATA_DIR\logs\stdout.log                     (raw uvicorn output)"
Write-Host "Uninstall : Unregister-ScheduledTask -TaskName '$taskName' -Confirm:`$false"
